project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('vocab.urls')),
]

vocab/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('review/<int:episode_id>', views.mark_episode_as_reviewed, name='episode_review'),
    path('episode/<slug:slug>/', views.episode_detail, name='episode_detail'),
    path('episodes/', views.episode_list, name='episode_list'),
    path('<slug:slug>/', views.entry_detail, name='entry_detail'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    def __str__(self):
        return self.email

vocab/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


class Episode(models.Model):
    """A session published by BBC News Review"""

    id = models.PositiveSmallIntegerField(
        primary_key=True,
        help_text="The session number on the BBC News Review website."
    )
    headline = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    date = models.DateField()
    raw_content = models.TextField()
    video = models.CharField(
        max_length=11,
        unique=True,
        null=True,
        help_text="The videoId from Youtube."
    )
    start_at = models.PositiveSmallIntegerField(
        blank=True,
        null=True,
        help_text="Second in which the summary starts."
    )

    def __str__(self):
        return f'{self.pk}. {self.headline} | {self.date}'

    def get_absolute_url(self):
        return reverse('episode_detail', kwargs={'slug': self.slug})


class Entry(models.Model):
    """The word or phrase presented in an Episode"""

    term = models.CharField(max_length=128, primary_key=True)
    slug = models.SlugField(max_length=128, unique=True)
    meaning = models.CharField(max_length=128)
    examples = models.TextField(max_length=510, blank=True)
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE)

    def __str__(self):
        return self.term

    def get_absolute_url(self):
        return reverse('entry_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.term)
        return super().save(*args, **kwargs)


class Review(models.Model):
    """Each time a user review an Episode"""

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE)
    when = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'email')

accounts/views.py
from django.shortcuts import render

# Create your views here.

vocab/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.sites.models import Site
from django.core.paginator import Paginator
from django.db import DatabaseError
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.decorators.http import require_POST

from vocab.models import Entry, Episode, Review


def index(request):
    return render(request, 'vocab/index.html')


def entry_detail(request, slug):
    return TemplateResponse(request, 'vocab/entry_detail.html', {
        'entry': get_object_or_404(Entry.objects.all(), slug=slug)
    })


def episode_detail(request, slug):
    episode = get_object_or_404(Episode.objects.all(), slug=slug)
    return TemplateResponse(request, 'vocab/episode_detail.html', {
        'episode': episode,
        'review_endpoint': reverse('episode_review', args=[episode.pk]),
    })


def episode_list(request):
    episodes = Episode.objects.order_by('-id')
    paginator = Paginator(episodes, 100)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'vocab/episode_list.html', {
        'page_obj': page_obj,
    })


@login_required
@require_POST
def mark_episode_as_reviewed(request, episode_id):
    try:
        Review.objects.create(user=request.user, episode_id=episode_id)
    except DatabaseError as e:
        print(f'Error saving the review: {e}')

    return HttpResponse(
        'Episode {episode_id} successfully marked reviewed by {request.user.username}',
        content_type='text/plain',
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.com/mvp.css">
  {% load static %}
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <title>{% block title %}News Review Tracker{% endblock %}</title>
</head>
<body>
  <header>
    <nav>
      <a href="/">News Review Tracker</a>
      <ul>
        <li><a href="{% url 'episode_list' %}">Episodes</a></li>
        <li><a href="#">About</a></li>
        {% if user.is_authenticated %}
          <li><a href="#">Account</a>
            <ul>
              <li><a href="#">Profile</a></li>
              <li><a href="{% url 'account_logout' %}">Logout</a></li>
            </ul>
          </li>
        {% endif %}
      </ul>
    </nav>
    {% if not user.is_authenticated %}
      <h1>Remember the <i>vocabulary</i><br>you learned on BBC News Review</h1>
      <p>
        <a href="{% url 'account_login' %}"><i>Log In</i></a>
        <a href="{% url 'account_signup' %}"><b>Sign Up</b></a>
      </p>
    {% endif %}
  </header>
  <main>
    {% block content %}{% endblock %}
  </main>
  {% block javascript %}{% endblock %}
</body>
</html>

vocab/templates/vocab/_review.html
<script>
  const button = document.getElementById('js-review-btn');

  const getCookie = (name) => {
    const cookie = document.cookie.split(';').find(
      (cookie) => cookie.trim().substring(0, name.length + 1) === `${name}=`);
    return decodeURIComponent(cookie.substring(name.length + 1));
  };

  const reviewEpisode = async () => {
    return fetch('{{ review_endpoint }}', {
      method: 'POST',
      headers: { 'X-CSRFToken': getCookie('csrftoken') },
      mode: 'same-origin'  // Do not send CSRF token to another domain.
    }).then((response) => response.ok);
  };

  const isUserAuthenticated = () => '{{ user.is_authenticated }}' === 'True';

  const handleClick = async (event) => {
    if (!isUserAuthenticated()) {
      const path = "{% url 'account_login' %}";
      const origin = window.location.origin;
      console.log("debug", path);
      window.location.replace(`${origin}${path}`);
    }

    try {
      await reviewEpisode();
      button.style.display = 'none';
    } catch (e) {
      console.log(`Error reviewing episode: ${e}`);
    }
  };

  window.onload = () => {
    button.style.display = 'inline-block';
    button.addEventListener('click', handleClick);
  }
</script>

vocab/templates/vocab/entry_detail.html
{% extends 'base.html' %}

{% block content %}
<article>
  <header>
    <h1>{{ entry.term }}</h1>
    <p><i>{{ entry.meaning }}</i></p>
  </header>
  <p class="examples">{{ entry.examples }}</p>
  <aside>
    <h2>Episode <a href="{% url 'episode_detail' entry.episode.slug %}">{{ entry.episode }}</a></h2>
  </aside>
</article>
{% endblock %}

vocab/templates/vocab/episode_detail.html
{% extends 'base.html' %}

{% block content %}
<article>
  <header>
    <h1>{{ episode.id }} - {{ episode.headline }}</h1>
  </header>

  {% for entry in episode.entry_set.all %}
    <p><a href="{% url 'entry_detail' entry.slug %}">{{ entry.term }}</a></p>
    <p><i>{{ entry.meaning }}</i></p>
    <hr>
  {% endfor %}

  <button id="js-review-btn">Mark as reviewed</button>

  <div class="videoWrapper">
    <iframe
      width="560"
      height="315"
      src="https://www.youtube.com/embed/{{ episode.video }}?start={{ episode.start_at }}"
      title="YouTube video player"
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen>
    </iframe>
  </div>
</article>
{% endblock %}

{% block javascript %}
  {{ block.super }}
  {% include 'vocab/_review.html' %}
{% endblock %}

vocab/templates/vocab/episode_list.html
{% extends 'base.html' %}

{% block content %}
<article>
  <header>
    <h1>Episodes</h1>
  </header>
  <table>
    <thead>
      <tr>
        <td>#</td>
        <td>Headline</td>
        <td>Date</td>
      </tr>
    </thead>
    <tbody>
      {% for episode in page_obj %}
      <tr>
        <td>{{ episode.id }}</td>
        <td><a href="{% url 'episode_detail' episode.slug %}">{{ episode.headline }}</a></td>
        <td>{{ episode.date }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
</article>
{% endblock %}

vocab/templates/vocab/index.html
{% extends 'base.html' %}

{% block content %}
<article>
  <h2>Terms to Revise</h2>
  <div class="row">
    <details>
      <summary>first term</summary>
        <p>the first term meaning</p>
        <p>Example 1</p>
        <p>Example 2</p>
    </details>
    <details>
      <summary>second term</summary>
        <p>the second term meaning</p>
        <p>Example 1</p>
        <p>Example 2</p>
    </details>
    <details>
      <summary>third term</summary>
        <p>the third term meaning</p>
        <p>Example 1</p>
        <p>Example 2</p>
    </details>
    <button>Mark all as revised</button>
    <form>
      <input type="search" name="search" placeholder="Search">
    </form>
  </div>
</article>
{% endblock %}